AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - 'bin/*'

Layout/SpaceAroundOperators:
  EnforcedStyleForExponentOperator: space
Lint/InheritException:
  Enabled: false
Naming/FileName:
  Exclude: [ lib/mqtt-ccutrer.rb ]
Style/Documentation:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/StringConcatenation:
  Enabled: false

Metrics:
  Enabled: false
