inherit_gem:
  rubocop-inst:
  - rubocop.yml
  - rubocop-rspec.yml

plugins:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1

Naming/FileName:
  Exclude: [ lib/mqtt-ccutrer.rb ]

RSpec/ContextWording:
  Prefixes:
    - that
    - when
    - with
    - without

Style/Documentation:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false
